# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: '$(Build.SourcesDirectory)'
    FodConnection: 'Prash_Test_Fortify'
    ReleaseOptions: '0'
    ReleaseId: 103101
    EntitlementSelection: '1'
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '0'
    BuildType: 'msbuild'
    BuildFile: 'eShopOnWeb.sln'
    PollingInterval: 0
    PolicyFailAction: '0'
  env:
    JAVA_HOME: $(JAVA_HOME_11_X64)
    PATH: $(JAVA_HOME_11_X64)/bin;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin;$(PATH)